#!/bin/sh

rm -f error.*

errorfile=error.$$

for i in *.inp; do

    case "$i" in
	*.rfn.inp )
	    continue
	    ;;
    esac

        echo " "
        echo "example ${i%.inp}"
        echo " "

#
#       removing the .lst file
#

	rm -f ${i%.inp}.lst

#
#       check whether the .dat and .dat.ref files exist
#
	if [ ! -f ${i%.inp}.dat ]; then
	   echo "${i%.inp}.dat does not exist" >> $errorfile
	   continue
        fi
	if [ ! -f ${i%.inp}.dat.ref ]; then
	   echo "${i%.inp}.dat.ref does not exist" >> $errorfile
	   continue
        fi
#
#       check whether the .dat and .dat.ref files have the same length
#

	export sum1=`wc -l ${i%.inp}.dat | awk '{print $1}'`
	export sum2=`wc -l ${i%.inp}.dat.ref | awk '{print $1}'`
	if [ $sum1 != $sum2 ]; then
	    echo "${i%.inp}.dat and ${i%.inp}.dat.ref do not have the same size !!!!!!!!!!" >> $errorfile
	    echo $sum1 >> $errorfile
	    echo $sum2 >> $errorfile
#	    cat ${i%.inp}.dat >> $errorfile
	   echo " ">> $errorfile
	   continue
        fi
#
#       check whether the .dat file contains NaN
#

	if grep "NaN" ${i%.inp}.dat ; then
	   echo "${i%.inp}.dat contains NaN !!!!!!!!!!" >> $errorfile
	   echo " " >> $errorfile
	   continue
        fi

#
#       check whether the numbers in the .dat and .dat.ref files
#       do not differ by more than a given amount (defined in file
#       datcheck.pl)
#
	./datcheck.pl ${i%.inp} >> $errorfile
#
#       check whether the .frd or the .frd.ref file exists
#
	if grep -q "^ -5" ${i%.inp}.frd  ||[ -f ${i%.inp}.frd.ref ] ; then
#
#           check that both files exist
#
	    if [ ! -f ${i%.inp}.frd ]; then
		echo "${i%.inp}.frd does not exist" >> $errorfile
		continue
            fi
	    if [ ! -f ${i%.inp}.frd.ref ]; then
		echo "${i%.inp}.frd.ref does not exist" >> $errorfile
		continue
            fi
#
#           check whether the .frd and .frd.ref files have the same length
#
	    
	    export sum1=`wc -l ${i%.inp}.frd | awk '{print$1}'`
	    export sum2=`wc -l ${i%.inp}.frd.ref | awk '{print$1}'`
	    if [ $sum1 != $sum2 ]; then
		echo "${i%.inp}.frd and ${i%.inp}.frd.ref do not have the same size !!!!!!!!!!!!!!!!!!!!!!" >> $errorfile
		echo " ">> $errorfile
		continue
            fi
#
#           check whether the numbers in the .frd and .frd.ref files
#           do not differ by more than a given amount (defined in file
#           frdcheck.pl)
#
	    ./frdcheck.pl ${i%.inp} >> $errorfile
            
        fi

done

rm -f beam10psmooth.rfn.inp
rm -f circ10dload.rfn.inp
rm -f circ10pcent.rfn.inp
rm -f circ10p.rfn.inp
rm -f circ10pnl.rfn.inp
rm -f segmentsmooth.rfn.inp
rm -f segmentsmooth3.rfn.inp
rm -f segmentsmooth2.rfn.inp
rm -f contact4tetrefine.rfn.inp
rm -f contact4bad.rfn.inp
rm -f contact4badnl.rfn.inp

echo "check the existence of file $errorfile"
echo "if this file does not exist, the present results"
echo "agree with the reference results"
echo " "
