#!/usr/bin/env python3
"""
Extract hinge rotations from a CalculiX .dat file (generated by generate_portal_eq_ccx.py).

It prints U3 (theta_z) for ROT nodes 1101..1104 and relative hinge rotations:
  dtheta_L = U3(1102) - U3(1101)
  dtheta_R = U3(1104) - U3(1103)
"""
import re, sys
from pathlib import Path

def parse_last_rot_block(text: str):
    # Find the last "displacements" block that includes nodes 1101..1104
    lines = text.splitlines()
    starts = [i for i,l in enumerate(lines) if "displacements" in l.lower()]
    if not starts:
        raise RuntimeError("No displacement blocks found")
    # scan from end to find a block containing 1101
    for s in reversed(starts):
        block = {}
        for i in range(s, min(s+5000, len(lines))):
            l = lines[i].strip()
            if not l:
                if block:
                    break
                continue
            parts = l.split()
            if len(parts) >= 4 and parts[0].isdigit():
                nid = int(parts[0])
                block[nid] = (float(parts[1]), float(parts[2]), float(parts[3]))
            # end heuristics
            if i > s and l.lower().startswith("displacements"):
                break
        if 1101 in block and 1102 in block and 1103 in block and 1104 in block:
            return block
    raise RuntimeError("Could not find a displacement block containing all ROT nodes 1101..1104")

def main(fn: str):
    text = Path(fn).read_text(encoding="utf-8", errors="ignore")
    blk = parse_last_rot_block(text)
    th = {nid: blk[nid][2] for nid in (1101,1102,1103,1104)}
    print("theta_z (rad) from ROT nodes (U3):")
    for nid in (1101,1102,1103,1104):
        print(f"  {nid}: {th[nid]: .6e}")
    dL = th[1102]-th[1101]
    dR = th[1104]-th[1103]
    print("\nHinge relative rotations:")
    print(f"  Left : dtheta = {dL:.6e} rad")
    print(f"  Right: dtheta = {dR:.6e} rad")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 post_hinge_theta.py <jobname.dat>")
        raise SystemExit(2)
    main(sys.argv[1])
